# -*- coding: utf-8 -*-
"""teste-YahooFinance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zXMrwpx2fG2Cf3bUBims1tDsdzlGODY
"""

!pip install yahooquery

from yahooquery import Ticker

petr=Ticker("PETR4.SA")
petr.income_statement()
petr = petr.income_statement().transpose()
petr.columns = petr.iloc[0,:]
petr=petr.iloc[2:,:-1]
petr=petr.iloc[:,::-1]
petr